import { GoogleGenAI } from '@google/genai';

export const DEMO_MODE = !process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === "your_key_here";

export const gemini = DEMO_MODE ? null : new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export function mockCandidates(disease: string, target: string, genotype: string) {
  return [
    { mol_id:"MOL-7743", name:"Benzimidazole-4-carboxamide derivative", smiles:"CC1=NC2=CC=CC=C2N1CC(=O)NC1=CC=C(F)C=C1", molecular_formula:"C16H14FN3O", molecular_weight:299.30, affinity_score:9.4, toxicity_pct:2.1, drug_likeness:"Passes", logP:2.34, hbd:2, hba:4, mechanism:`Competitively inhibits the active site of ${target}, blocking substrate binding with high selectivity.`, explanation:`MOL-7743 demonstrates exceptional binding affinity to ${target} through hydrogen bonding with key residues. ${genotype?`The fluorine substituent improves metabolic stability for patients with ${genotype}.`:"Favorable ADMET across diverse populations."} Recommended: in vitro IC50 determination.`, rank:1 },
    { mol_id:"MOL-3891", name:"Pyrimidine-2-amine scaffold", smiles:"CN1CCN(CC1)C1=NC(=NC=C1)NC1=CC=CC(=C1)Cl", molecular_formula:"C15H18ClN5", molecular_weight:307.79, affinity_score:9.1, toxicity_pct:3.8, drug_likeness:"Passes", logP:2.71, hbd:1, hba:5, mechanism:`Allosteric modulator of ${target}, inducing conformational changes that reduce enzymatic activity by 87%.`, explanation:`This pyrimidine derivative exploits an allosteric pocket adjacent to the ${target} active site. Piperazine ring enhances aqueous solubility while chloro-phenyl provides hydrophobic contacts. >100-fold selectivity over off-targets confirmed.`, rank:2 },
    { mol_id:"MOL-5520", name:"Thienopyrimidine sulfonamide", smiles:"O=S(=O)(NC1=CC=C(N)C=C1)C1=CC2=C(N=CN=C2)S1", molecular_formula:"C11H10N4O2S2", molecular_weight:294.35, affinity_score:8.7, toxicity_pct:5.2, drug_likeness:"Passes", logP:1.89, hbd:3, hba:6, mechanism:`Reversible ATP-competitive inhibitor of ${target} with nanomolar potency (Ki = 12 nM).`, explanation:`Thienopyrimidine core mimics the adenine moiety of ATP, enabling tight binding to the hinge region of ${target}. Sulfonamide improves blood-brain barrier penetration. Moderate CYP3A4 metabolism — monitoring recommended.`, rank:3 },
    { mol_id:"MOL-2214", name:"Indazole-piperidinyl carboxylate", smiles:"O=C(OCC)C1CCN(CC1)C1=NN=C2C=CC=CC2=C1", molecular_formula:"C15H17N3O2", molecular_weight:271.32, affinity_score:8.2, toxicity_pct:8.1, drug_likeness:"Passes", logP:2.15, hbd:0, hba:4, mechanism:`Selective partial agonist at ${target}, modulating downstream signaling with reduced on-target toxicity.`, explanation:`Indazole scaffold provides selectivity for ${target}. Piperidinyl ester prodrug design improves oral bioavailability (predicted F = 68%). T₁/₂ > 60 min in human liver microsomes. Partial agonism offers wider therapeutic window.`, rank:4 },
    { mol_id:"MOL-9033", name:"Quinoxaline-fused heterocycle", smiles:"O=C1NC2=CC=CC=C2N=C1SCC1=CC=CO1", molecular_formula:"C13H9N3O2S", molecular_weight:271.29, affinity_score:7.9, toxicity_pct:11.4, drug_likeness:"Partial", logP:3.42, hbd:1, hba:4, mechanism:`Covalent irreversible inhibitor forming thioether bond with Cys residue in ${target} binding pocket.`, explanation:`Covalent warhead strategy provides extended duration (>24h) reducing dosing frequency. Furan ring shows 15% GSH depletion at 10μM — electrophilic trap optimization needed. Macrocyclic analogs recommended for improved selectivity.`, rank:5 },
  ];
}
