export const DRUGS_DB = [
  {id:1,name:"Aspirin",generic:"Acetylsalicylic acid",smiles:"CC(=O)Oc1ccccc1C(=O)O",formula:"C9H8O4",mw:180.16,cat:"Anti-inflammatory",catKey:"av",indication:"Pain, fever, inflammation, cardiovascular prevention",target:"COX-1, COX-2",mechanism:"Irreversibly inhibits cyclooxygenase enzymes, blocking prostaglandin synthesis and platelet aggregation.",approved:1899,company:"Bayer",logP:1.19,halfLife:"15–20 min (3–10h salicylate)",hbd:1,hba:4,description:"One of the oldest drugs in existence, aspirin's antiplatelet action makes it foundational in cardiovascular medicine alongside its analgesic and anti-inflammatory properties."},
  {id:2,name:"Ibuprofen",generic:"Ibuprofen",smiles:"CC(C)Cc1ccc(cc1)C(C)C(=O)O",formula:"C13H18O2",mw:206.28,cat:"Anti-inflammatory",catKey:"av",indication:"Pain, fever, arthritis, dysmenorrhea",target:"COX-1, COX-2",mechanism:"Reversible, non-selective COX inhibitor reducing prostaglandin and thromboxane synthesis.",approved:1969,company:"Boots",logP:3.97,halfLife:"1.8–2h",hbd:1,hba:2,description:"A widely used NSAID with strong analgesic and anti-inflammatory activity. OTC availability and favorable profile make it among the most consumed drugs globally."},
  {id:3,name:"Atorvastatin",generic:"Atorvastatin calcium",smiles:"CC(C)c1c(C(=O)Nc2ccccc2F)c(-c2ccccc2)n(CC[C@@H](O)C[C@@H](O)CC(=O)O)c1-c1ccc(F)cc1",formula:"C33H35FN2O5",mw:558.64,cat:"Cardiovascular",catKey:"cv",indication:"Hypercholesterolemia, cardiovascular disease prevention",target:"HMG-CoA Reductase",mechanism:"Competitively inhibits HMG-CoA reductase, the rate-limiting enzyme in cholesterol biosynthesis.",approved:1996,company:"Pfizer",logP:6.36,halfLife:"14h",hbd:2,hba:7,description:"The world's best-selling drug for over a decade (Lipitor). Dramatically reduces LDL cholesterol and cardiovascular events. Cornerstone of preventive cardiology."},
  {id:4,name:"Metformin",generic:"Metformin hydrochloride",smiles:"CN(C)C(=N)NC(=N)N",formula:"C4H11N5",mw:129.16,cat:"Metabolic",catKey:"meta",indication:"Type 2 diabetes, PCOS, insulin resistance",target:"AMPK, Complex I (mitochondrial)",mechanism:"Activates AMPK, inhibiting hepatic gluconeogenesis and improving peripheral insulin sensitivity.",approved:1957,company:"Various",logP:-1.43,halfLife:"4–8.7h",hbd:5,hba:1,description:"First-line pharmacotherapy for type 2 diabetes. Unique mechanism via AMPK activation. Also investigated for cancer prevention and longevity — one of medicine's most versatile molecules."},
  {id:5,name:"Imatinib",generic:"Imatinib mesylate",smiles:"Cc1ccc(NC(=O)c2ccc(CN3CCN(C)CC3)cc2)cc1Nc1nccc(-c2cccnc2)n1",formula:"C29H31N7O",mw:493.60,cat:"Oncology",catKey:"onc",indication:"CML, GIST, Ph+ ALL",target:"BCR-ABL, c-KIT, PDGFR",mechanism:"ATP-competitive kinase inhibitor that selectively blocks BCR-ABL tyrosine kinase in CML cells.",approved:2001,company:"Novartis",logP:3.74,halfLife:"18–40h",hbd:2,hba:7,description:"Gleevec — the drug that transformed CML from a fatal disease to a manageable chronic condition. Proof-of-concept for targeted cancer therapy and the first successful kinase inhibitor."},
  {id:6,name:"Omeprazole",generic:"Omeprazole",smiles:"CC1=CN=C(C(COc2ccc(OC)cc2OC)=N1)Cc1ncc(C)c(OC)n1",formula:"C17H19N3O3S",mw:345.42,cat:"Gastrointestinal",catKey:"other",indication:"GERD, peptic ulcer, H. pylori eradication",target:"H+/K+-ATPase (proton pump)",mechanism:"Irreversible proton pump inhibitor — forms covalent disulfide bond with cysteine residues of H+/K+-ATPase.",approved:1989,company:"AstraZeneca",logP:2.23,halfLife:"0.5–1h (effects last 24h)",hbd:1,hba:7,description:"The first proton pump inhibitor (Prilosec). Revolutionized treatment of acid-related disorders. Remains among the most prescribed drugs globally decades after approval."},
  {id:7,name:"Sertraline",generic:"Sertraline hydrochloride",smiles:"CNC1CCC(c2ccc(Cl)cc2Cl)c2ccccc21",formula:"C17H17Cl2N",mw:306.23,cat:"CNS",catKey:"cns",indication:"Depression, OCD, PTSD, panic disorder",target:"Serotonin transporter (SERT)",mechanism:"Selective serotonin reuptake inhibitor, increasing synaptic serotonin availability.",approved:1991,company:"Pfizer",logP:5.29,halfLife:"26h",hbd:1,hba:1,description:"Zoloft — one of the most prescribed antidepressants. Favorable safety profile makes it first-line for depression, anxiety disorders, and PTSD."},
  {id:8,name:"Remdesivir",generic:"Remdesivir (GS-5734)",smiles:"CCC(CC)COC(=O)[C@@H](N[P@@](=O)(Oc1ccccc1)N)C[C@@H]1OC(n2cc(F)c(N)n2)[C@@H]1O",formula:"C27H35FN6O8P",mw:602.58,cat:"Antiviral",catKey:"av",indication:"COVID-19, Ebola (investigational)",target:"RNA-dependent RNA polymerase (RdRp)",mechanism:"Nucleotide analog prodrug that incorporates into viral RNA, causing chain termination during replication.",approved:2020,company:"Gilead",logP:1.9,halfLife:"1h (active metabolite 24.5h)",hbd:3,hba:11,description:"First FDA-approved COVID-19 treatment. Adenosine analog that inhibits viral RdRp with broad-spectrum antiviral activity. Demonstrates the utility of nucleotide prodrug strategies."},
  {id:9,name:"Nirmatrelvir",generic:"Nirmatrelvir (PF-07321332)",smiles:"CC1(C2CC1(N(C2)C(=O)[C@@H](NC(=O)[C@H](CC3CCNC3=O)NC(=O)N4CC(C4)F)C(C)(C)C)C#N)C",formula:"C23H32F3N5O4",mw:499.53,cat:"Antiviral",catKey:"av",indication:"COVID-19 (mild-to-moderate)",target:"SARS-CoV-2 Main Protease (Mpro)",mechanism:"Covalent, reversible inhibitor of SARS-CoV-2 Mpro, preventing viral polyprotein cleavage.",approved:2021,company:"Pfizer",logP:1.69,halfLife:"6.1h",hbd:3,hba:8,description:"Paxlovid component — the most clinically impactful oral COVID-19 antiviral. Designed entirely in silico using structure-based drug design. A landmark in AI-assisted drug discovery."},
  {id:10,name:"Pembrolizumab",generic:"Pembrolizumab",smiles:"(Large IgG4 monoclonal antibody — SMILES not applicable)",formula:"Monoclonal antibody",mw:148000,cat:"Oncology",catKey:"onc",indication:"Melanoma, NSCLC, multiple cancers",target:"PD-1 checkpoint",mechanism:"IgG4 monoclonal antibody blocking PD-1/PD-L1 interaction, restoring T-cell anti-tumor immunity.",approved:2014,company:"Merck",logP:"N/A",halfLife:"26 days",hbd:"N/A",hba:"N/A",description:"Keytruda — the best-selling cancer immunotherapy. Checkpoint inhibitor that unleashes T-cells against tumors. Approved for 40+ indications, redefining cancer treatment."},
  {id:11,name:"Dexamethasone",generic:"Dexamethasone",smiles:"C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@H]3[C@@H](O)C[C@]2(C)[C@@H]1C(=O)CO",formula:"C22H29FO5",mw:392.46,cat:"Anti-inflammatory",catKey:"av",indication:"Inflammation, autoimmune disease, COVID-19 severe cases",target:"Glucocorticoid receptor (GR)",mechanism:"Binds glucocorticoid receptor, translocating to nucleus and modifying transcription of pro-inflammatory genes.",approved:1961,company:"Merck",logP:1.83,halfLife:"36–54h",hbd:2,hba:5,description:"Potent synthetic glucocorticoid. Saved lives in COVID-19 severe cases — the first treatment proven to reduce mortality. Also pivotal in autoimmune conditions, chemotherapy antiemesis, and edema."},
  {id:12,name:"Methotrexate",generic:"Methotrexate (MTX)",smiles:"CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)N[C@@H](CCC(=O)O)C(=O)O)cc1",formula:"C20H22N8O5",mw:454.44,cat:"Oncology",catKey:"onc",indication:"ALL, NHL, breast cancer, RA, psoriasis",target:"Dihydrofolate reductase (DHFR)",mechanism:"Competitive inhibitor of DHFR, depleting tetrahydrofolate essential for purine and thymidylate synthesis.",approved:1953,company:"Various",logP:-1.85,halfLife:"3–10h",hbd:5,hba:11,description:"Dual-use drug in oncology (high-dose) and autoimmune disease (low-dose). A cornerstone of modern chemotherapy regimens and disease-modifying therapy for RA."},
  {id:13,name:"Liraglutide",generic:"Liraglutide",smiles:"(Peptide — SMILES omitted)",formula:"C172H265N43O51",mw:3751.2,cat:"Metabolic",catKey:"meta",indication:"Type 2 diabetes, obesity (Victoza/Saxenda)",target:"GLP-1 receptor",mechanism:"GLP-1 receptor agonist stimulating insulin secretion, inhibiting glucagon, and reducing gastric emptying.",approved:2010,company:"Novo Nordisk",logP:"N/A",halfLife:"13h",hbd:"N/A",hba:"N/A",description:"Victoza/Saxenda — GLP-1 agonist that transformed both diabetes management and obesity treatment. Predecessor to the semaglutide (Ozempic) revolution reshaping metabolic medicine."},
  {id:14,name:"Warfarin",generic:"Warfarin sodium",smiles:"OC(=O)c1ccccc1CCC(=O)/C=C/c1ccc(OC(=O)C)cc1",formula:"C19H16O4",mw:308.33,cat:"Cardiovascular",catKey:"cv",indication:"Atrial fibrillation, DVT, PE, mechanical heart valves",target:"Vitamin K epoxide reductase (VKOR)",mechanism:"Inhibits vitamin K epoxide reductase, blocking activation of clotting factors II, VII, IX, X.",approved:1954,company:"Various",logP:2.7,halfLife:"20–60h",hbd:1,hba:4,description:"Most widely used oral anticoagulant for decades. Narrow therapeutic window requires regular INR monitoring. Epitomizes the precision required in anticoagulation therapy."},
  {id:15,name:"Sildenafil",generic:"Sildenafil citrate",smiles:"CCCC1=NN(C)C(=C1C(=O)NCC2=CC(=CC=C2OCC)S(=O)(=O)N3CCN(C)CC3)c1cc(ccc1OCC)S(=O)(=O)N1CCN(C)CC1",formula:"C22H30N6O4S",mw:474.58,cat:"Cardiovascular",catKey:"cv",indication:"Erectile dysfunction, pulmonary arterial hypertension",target:"PDE5 (phosphodiesterase type 5)",mechanism:"Selective PDE5 inhibitor increasing cGMP levels, causing smooth muscle relaxation and vasodilation.",approved:1998,company:"Pfizer",logP:1.9,halfLife:"3–5h",hbd:1,hba:7,description:"Viagra — discovered serendipitously during angina trials. One of the most profitable drugs in history and a landmark demonstration of repurposing. Also FDA-approved for pulmonary hypertension (Revatio)."},
];

export const TARGETS_DB = [
  {id:1,name:"SARS-CoV-2 Mpro",full:"Main Protease (3CL protease)",gene:"Nsp5",type:"Protease",diseaseArea:"Antiviral",diseases:["COVID-19","SARS"],approvedDrugs:["Nirmatrelvir (Paxlovid)"],pdbId:"6LU7",description:"The main protease of SARS-CoV-2 is essential for viral replication, cleaving the viral polyprotein at 11 sites. Its active site contains conserved Cys145-His41 catalytic dyad — an attractive drug target with no human homolog."},
  {id:2,name:"BCR-ABL",full:"BCR-ABL1 Fusion Tyrosine Kinase",gene:"BCR-ABL1",type:"Tyrosine Kinase",diseaseArea:"Oncology",diseases:["CML","Ph+ ALL"],approvedDrugs:["Imatinib","Dasatinib","Nilotinib","Ponatinib"],pdbId:"2HYY",description:"Constitutively active tyrosine kinase resulting from the Philadelphia chromosome translocation t(9;22). The founding target of the kinase inhibitor revolution in oncology."},
  {id:3,name:"PD-1 / PD-L1",full:"Programmed Cell Death Protein 1",gene:"PDCD1",type:"Checkpoint Receptor",diseaseArea:"Oncology (Immunotherapy)",diseases:["Melanoma","NSCLC","Bladder cancer","40+ tumor types"],approvedDrugs:["Pembrolizumab","Nivolumab","Atezolizumab"],pdbId:"4ZQK",description:"PD-1 is an immune checkpoint that cancer cells exploit to evade T-cell killing. Blocking the PD-1/PD-L1 axis restores anti-tumor immunity — the basis of the checkpoint inhibitor revolution."},
  {id:4,name:"HMG-CoA Reductase",full:"3-Hydroxy-3-methyl-glutaryl-CoA reductase",gene:"HMGCR",type:"Enzyme",diseaseArea:"Cardiovascular",diseases:["Hypercholesterolemia","Cardiovascular disease","Familial hypercholesterolemia"],approvedDrugs:["Atorvastatin","Rosuvastatin","Simvastatin","Pravastatin"],pdbId:"1HWK",description:"Rate-limiting enzyme in the mevalonate pathway for cholesterol biosynthesis. Statin inhibitors have prevented millions of cardiovascular events, making this one of the most clinically impactful drug targets."},
  {id:5,name:"EGFR",full:"Epidermal Growth Factor Receptor",gene:"EGFR",type:"RTK",diseaseArea:"Oncology",diseases:["NSCLC","Colorectal cancer","Head & neck cancer","Glioblastoma"],approvedDrugs:["Gefitinib","Erlotinib","Osimertinib","Cetuximab"],pdbId:"1IVO",description:"Receptor tyrosine kinase overexpressed or mutated in multiple cancers. EGFR-mutant NSCLC (exon 19/21 mutations) responds dramatically to TKIs, transforming outcomes for this patient subset."},
  {id:6,name:"BACE1",full:"Beta-Site APP Cleaving Enzyme 1",gene:"BACE1",type:"Aspartyl Protease",diseaseArea:"CNS / Neurology",diseases:["Alzheimer's disease"],approvedDrugs:["None approved (multiple failed Phase 3)"],pdbId:"1FKN",description:"Key enzyme in amyloid precursor protein cleavage producing Aβ peptides central to Alzheimer's pathology. Despite extensive drug discovery efforts, no BACE1 inhibitor has succeeded in Phase 3 — largely due to mechanism-based side effects."},
  {id:7,name:"COX-1 / COX-2",full:"Cyclooxygenase 1 and 2",gene:"PTGS1, PTGS2",type:"Enzyme",diseaseArea:"Inflammation",diseases:["Arthritis","Acute pain","Cardiovascular disease","Cancer prevention"],approvedDrugs:["Aspirin","Ibuprofen","Celecoxib","Naproxen"],pdbId:"1CQE",description:"Cyclooxygenase enzymes convert arachidonic acid to prostaglandins and thromboxanes. COX-2 selective inhibitors (coxibs) were developed to reduce GI side effects, though cardiovascular risks emerged."},
  {id:8,name:"PARP1",full:"Poly(ADP-ribose) Polymerase 1",gene:"PARP1",type:"Nuclear Enzyme",diseaseArea:"Oncology",diseases:["BRCA-mutant breast/ovarian cancer","Prostate cancer","Pancreatic cancer"],approvedDrugs:["Olaparib","Niraparib","Rucaparib","Talazoparib"],pdbId:"4DQY",description:"Key enzyme in DNA damage repair. PARP inhibitors exploit synthetic lethality in BRCA1/2-mutant tumors, where homologous recombination deficiency plus PARP inhibition leads to catastrophic DNA damage in cancer cells only."},
  {id:9,name:"GLP-1R",full:"Glucagon-Like Peptide-1 Receptor",gene:"GLP1R",type:"GPCR",diseaseArea:"Metabolic",diseases:["Type 2 diabetes","Obesity","Cardiovascular disease"],approvedDrugs:["Semaglutide","Liraglutide","Dulaglutide","Tirzepatide"],pdbId:"5VAI",description:"Class B GPCR mediating incretin effects. GLP-1 agonists have become blockbuster drugs for diabetes and obesity, with semaglutide (Ozempic/Wegovy) achieving unprecedented weight loss — and redefining metabolic medicine."},
  {id:10,name:"VEGFR-2",full:"Vascular Endothelial Growth Factor Receptor 2",gene:"KDR",type:"RTK",diseaseArea:"Oncology / Vascular",diseases:["Colorectal cancer","NSCLC","Renal cell carcinoma","Wet AMD"],approvedDrugs:["Bevacizumab","Sunitinib","Sorafenib","Axitinib"],pdbId:"2OH4",description:"Primary mediator of tumor angiogenesis. Anti-angiogenic strategies targeting VEGF/VEGFR2 were among the first non-cytotoxic cancer therapies, demonstrating that cutting tumor blood supply is a viable treatment approach."},
  {id:11,name:"ACE2",full:"Angiotensin-Converting Enzyme 2",gene:"ACE2",type:"Carboxypeptidase",diseaseArea:"Cardiovascular / Antiviral",diseases:["COVID-19 (receptor)","Hypertension","Heart failure"],approvedDrugs:["(No approved inhibitors; SARS-CoV-2 entry target)"],pdbId:"1R42",description:"Dual role: physiologically converts angiotensin II to angiotensin-(1-7), conferring cardioprotection. Also serves as the primary receptor for SARS-CoV-2 spike protein entry, making it central to COVID-19 pathogenesis."},
  {id:12,name:"mTOR",full:"Mechanistic Target of Rapamycin",gene:"MTOR",type:"Serine/Threonine Kinase",diseaseArea:"Oncology / Transplant",diseases:["Renal cell carcinoma","Breast cancer","Organ rejection","TSC"],approvedDrugs:["Temsirolimus","Everolimus","Rapamycin (sirolimus)"],pdbId:"4JT6",description:"Master regulator of cell growth, proliferation, and survival integrating nutrient, energy, and growth factor signals. Both allosteric (rapalogs) and ATP-competitive (TORKi) inhibitors have been developed."},
];

export const DRUG_FACTS = [
  "The word 'pharmacy' derives from the Greek pharmakeia — the use of drugs, spells, or poison.",
  "Penicillin, discovered by Fleming in 1928, has saved an estimated 200 million lives.",
  "The human genome contains ~20,000 protein-coding genes, but only ~700 have been targeted by approved drugs.",
  "Aspirin is taken by 40 million Americans daily as cardiovascular prevention therapy.",
  "It costs $1–2.6B and takes 12 years on average to develop a new drug — but AI is changing this.",
  "Only 1 in 5,000 compounds that enter preclinical testing will become an approved drug.",
  "The top 10 selling drugs globally generate over $100B in annual revenue combined.",
  "AlphaFold2 (2020) predicted structures for 200M+ proteins — accelerating structure-based drug discovery immensely.",
  "Metformin, approved in 1957, is now being investigated for potential anti-aging properties.",
  "The FDA approves ~50 new drugs per year, but most are incremental improvements rather than first-in-class.",
];

export const NEWS_FEED = [
  {tag:"AI Drug Discovery",title:"DeepMind's AlphaFold3 predicts protein-ligand interactions with record accuracy",source:"Nature · 2025",url:"#"},
  {tag:"Clinical Trial",title:"AI-designed MDM2 inhibitor enters Phase II for p53-wild type cancers",source:"ASCO · 2025",url:"#"},
  {tag:"Oncology",title:"KRAS G12C inhibitors show durable responses in NSCLC with novel combination strategies",source:"NEJM · 2025",url:"#"},
  {tag:"Generative AI",title:"Diffusion models generate drug-like molecules with 90% synthetic accessibility",source:"J. Med. Chem. · 2025",url:"#"},
  {tag:"Regulatory",title:"FDA issues new guidance for AI/ML-based drug discovery submissions",source:"FDA · 2025",url:"#"},
];

export const MARKET_DATA = [
  {label:"Drug Discovery Market (2030)", val:"$1.5T"},
  {label:"AI in Drug Discovery (2030)", val:"$12B"},
  {label:"Avg. Drug Dev. Cost", val:"$1.9B"},
  {label:"Rare Diseases (No Treatment)", val:"7,000+"},
  {label:"AI Market CAGR", val:"42%"},
];
